### ISSUE TITLE
questions about codes

### ISSUE THREAD

**Issue by sumfish0104** [LI-Hao-SJTU/DerainRLNet#2]
hello，i am learning to use deep learning to derain and i have read your paper and code for a week. However, i am still confused about some codes. I would appreciate it if you can solve my problem. Here are the problems:
①：x9 = torch.cat([x9,h_f,h_f,h_f,h_f,h_f,h_f],1)  why is the h_f cascaded six times?
       x_223 = torch.cat([xa2,x_3,x_3,x_3],1)          why is the x_3 cascaded three times?

②：In Dense_base_down00/11/22         
        self.dense_block5=BottleneckBlock2(57,24)
        self.trans_block5=TransitionBlock(81,24)
why is BottleneckBlock's input channel 57? and my calculation is 51

I don't know if i'm asking stupid questions. I study on my own and i really want to understand all of you paper and code. Thank you very much

**Comment by LI-Hao-SJTU** [comment]
Thanks for your interests. We have checked the details again and there is no mistake.
