### ISSUE TITLE
您好，请问可以提供预训练模型吗/

### ISSUE THREAD

**Issue by hotdjboy** [LI-Hao-SJTU/DerainRLNet#7]

**Comment by LI-Hao-SJTU** [comment]
谢谢关注 ~~ 但是目前，我们恐怕无权公开a pre-trained model，抱憾

**Comment by hotdjboy** [comment]
好的，感谢答复!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LI-Hao-SJTU/DerainRLNet] 您好，请问可以提供预训练模型吗/ (Issue #7)




 
谢谢关注 ~~ 但是目前，我们恐怕无权公开a pre-trained model，抱憾

**Comment by hotdjboy** [comment]
v好的，感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LI-Hao-SJTU/DerainRLNet] 您好，请问可以提供预训练模型吗/ (Issue #7)




 
谢谢关注 ~~ 但是目前，我们恐怕无权公开a pre-trained model，抱憾
